### ISSUE TITLE
URI::InvalidURIError - bad URI(is not URI?): http://myhorizon.solorient.com.au/Horizon/@@horizondap_lpsc@@/atdis/1.0/applications.json/applications.json/applications.json?last_modified_date_end=&last_modified_date_start=&lodgement_date_end=&lodgement_date_star...

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts-app#594]
## Backtrace

    line 46 of [PROJECT_ROOT]/app/models/feed.rb: create_from_url
    line 4 of [PROJECT_ROOT]/app/controllers/atdis_controller.rb: test

[View full backtrace and more info at honeybadger.io](https://www.honeybadger.io/projects/37075/faults/8569005)

**Comment by mlandauer** [comment]
I think this is fixed. Going to close
