### ISSUE TITLE
replace the Tweets section with a call for donations

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts-app#607]
Following planningalerts on twitter is a way to stay up-to-date date with new authorities being added, promotions of other civic tech activities and down time to the application. Not many people follow the account currently, and we know that many people using PlanningAlerts aren't interested in civic tech more widely. Twitter is a good way for people to contact OAF about broken scrapers or ask questions, but the contact or about page would be a more logical place to look for this.

This section could instead feature a sentence explaining that the site is independent and charity run and call on people who find it useful to donate—contributing to the improvement of the service and becoming more connected to it. This gives citizens more information about how the project works, putting them in a better position to support the project if they find it useful (a number of users have said they thought the project was supported by councils/government).

**Comment by henare** [comment]
Nice idea and background.

**Comment by equivalentideas** [comment]
I'm going to go ahead with this as a PR

**Comment by equivalentideas** [comment]
Any thoughts on this idea @mlandauer @kat :

![screen shot 2015-01-21 at 5 12 02 pm](https://cloud.githubusercontent.com/assets/1239550/5831942/c335405e-a190-11e4-807b-cf1c3779e41b.png)

**Comment by mlandauer** [comment]
I like donate banner. Not 100% convinced that getting rid of the twitter feed is a good idea though.

Would it be possible to make the text more scannable so you can pick up the key words without reading the whole text?

**Comment by henare** [comment]
>I like donate banner. Not 100% convinced that getting rid of the twitter feed is a good idea though.

The twitter feed has been broken for ages - since Twitter stupidly got rid of RSS feeds. At the moment it looks like this on PlanningAlerts:

![selection_001](https://cloud.githubusercontent.com/assets/48945/5869210/7f65c6e4-a309-11e4-8411-279a856b6abf.png)

So I'm happy for this replacement.

However, I'd like to replace the "News" section with items from the Twitter feed instead of the blog since it's so rarely updated - the latest entry is from over a year ago! At least the twitter feed is a bit more current.

>Would it be possible to make the text more scannable so you can pick up the key words without reading the whole text?

Love it  :octopus:

**Comment by equivalentideas** [comment]
> However, I'd like to replace the "News" section with items from the Twitter feed instead of the blog since it's so rarely updated - the latest entry is from over a year ago! At least the twitter feed is a bit more current.

I'm happy with that.

> Would it be possible to make the text more scannable so you can pick up the key words without reading the whole text?

I'm quite happy with the copy:

> This independent project is run by a local charity, the OpenAustralia Foundation. PlanningAlerts is powered by small donations from the people who use it to stay informed about changes to their local area. If you find it useful, chip in to support PlanningAlerts.

I actually think it's good to slow people down and get them to read this. We want them to take in these points about why they should donate:

* The opening highlights that this isn't gov or gov funded (something users have described confusion about) and sign-post that they'll be sent over to OAF site to donate.
* The second sentence connects to the way people described what is important about PlanningAlerts, it "informs" them about their "local area" and makes donating positive.
* gives them ownership of the service, they're powering it.
* final sentence connects the points back to the heading.

**Comment by equivalentideas** [comment]
I'm going to make this PR and we can continue discussion there if there are blockers.

I'll just remove the render of the twitter partial, which we can fix and move to the news section or do something else with. I think it's a negative sitting there broken.

**Comment by henare** [comment]
>The twitter feed has been broken for ages - since Twitter stupidly got rid of RSS feeds. At the moment it looks like this on PlanningAlerts

Turns out I was wrong - we fixed it after the RSS stupidity but somewhere it got commented out and never turned back on! Oops.

https://github.com/openaustralia/planningalerts-app/blob/master/app/views/shared/_tweets.haml#L8
