### ISSUE TITLE
https everywhere on planning alerts

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts-app#624]

**Comment by mlandauer** [comment]
At an absolute minimum we're going to need to enforce ssl for any payment page

**Comment by equivalentideas** [comment]
That's #623 . @henare and I were talking about this yesterday.

I don't know if it would be easier to turn it on for whole app or just that page (and thank you page?).

**Comment by mlandauer** [comment]
Much the same. I'd be keen to get it working across the whole site.

**Comment by equivalentideas** [comment]
:+1: :+1: :+1:

**Comment by mlandauer** [comment]
The plan for today is to get a new certificate for www.planningalerts.org.au/planningalerts.org.au and api.planningalerts.org.au/planningalerts.org.au

Then, once that's working force ssl on everything other than the api requests (on both domains)

Then, update the email alerts to send out https links. They'll still be rewritten as http links by cuttlefish but then after cuttlefish it will be an https link.

**Comment by mlandauer** [comment]
@henare @equivalentideas I've added SSL for https://www.planningalerts.org.au and the api (e.g. https://api.planningalerts.org.au/applications.js?address=24+Bruce+Road+Glenbrook%2C+NSW+2773&radius=4000)

I would appreciate it if you could test the site and double check that everything is working as expected. As per normal I've had to update any third party js/images to https and I just want to make sure I haven't missed anything.

Once you've both had a look I'll start on rolling out the redirects to SSL so everyone will be forced to use SSL.

**Comment by henare** [comment]
Looks good to me :eyes:

**Comment by equivalentideas** [comment]
All seems to be working for me. Nice one!

**Comment by mlandauer** [comment]
@henare @equivalentideas next stage done. Now SSL is forced on everything other than the api and nsw theme. (nsw theme is broken atm for another reason). Please double check that I haven't broken anything.

**Comment by henare** [comment]
:metal:

**Comment by mlandauer** [comment]
This looks to be all done now
