### ISSUE TITLE
Twitter::Error::ClientError - execution expired

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts-app#631]
## Backtrace

    line 11 of [PROJECT_ROOT]/app/models/twitter_feed.rb: feed
    line 18 of [PROJECT_ROOT]/app/models/twitter_feed.rb: items
    line 60 of [PROJECT_ROOT]/app/helpers/application_helper.rb: render_twitter_feed

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37075/faults/11032435)

**Comment by mlandauer** [comment]
We catch any errors and ignore them now
