### ISSUE TITLE
The new account sign in & register pages are broken on mobile

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts-app#643]
They're just about legible but certainly not functional or good

**Comment by mlandauer** [comment]
The current code is on the [user_signup branch](https://github.com/openaustralia/planningalerts-app/tree/user_signup)

The two most important pages are:
* http://localhost:3000/users/sign_in
* http://localhost:3000/users/sign_up

@equivalentideas could you please have a look at this quickly this afternoon?

**Comment by equivalentideas** [comment]
I see what you mean. The form labels are squashing into the inputs:

![screen shot 2015-02-27 at 3 52 29 pm](https://cloud.githubusercontent.com/assets/1239550/6407650/abca4372-be98-11e4-9dd2-b325c74ff3d4.png)

**Comment by mlandauer** [comment]
I think with all the other forms on the site we did laid out the forms differently on mobile. For example look at https://www.planningalerts.org.au/alerts/signup

**Comment by equivalentideas** [comment]
Yep, there's a section in _grid.scss that overrides the default styles for the alerts form.

They become functional by simply adding the selector for this group of forms `form.user` to that block of styles.

**Comment by equivalentideas** [comment]
I'm testing this against all the user forms

**Comment by equivalentideas** [comment]
That fixes the label wrapping issue, and aligns the form to the centre (like the alerts form):

![screen shot 2015-02-27 at 4 22 53 pm](https://cloud.githubusercontent.com/assets/1239550/6407854/0124ef26-be9d-11e4-9f69-9e153a9c9d5b.png)

There is another issue that label test isn't wrapping when it is very long:
![screen shot 2015-02-27 at 4 22 34 pm](https://cloud.githubusercontent.com/assets/1239550/6407860/19847d20-be9d-11e4-90e2-3e9d57dfeb31.png)

**Comment by equivalentideas** [comment]
Got it with css `white-space: normal`:

![screen shot 2015-02-27 at 4 44 23 pm](https://cloud.githubusercontent.com/assets/1239550/6407991/ee45c9b8-be9f-11e4-882e-f08ca6e7e235.png)

**Comment by equivalentideas** [comment]
@mlandauer do you want me to PR that or push it straight onto `user_signup`?

**Comment by mlandauer** [comment]
@equivalentideas I notice the "remember me" is not getting properly centered on all mobile screen sizes

**Comment by equivalentideas** [comment]
I see what you mean, the full width of it is being centred, 

![screen shot 2015-02-27 at 5 03 20 pm](https://cloud.githubusercontent.com/assets/1239550/6408157/af6c707c-bea2-11e4-9ebc-24e143a51c2a.png)

The problem is it's not getting court in the other style because formtastic handles checkboxes differently from other inputs.

I'll fix that now.

**Comment by equivalentideas** [comment]
This is now centred consistently:

![screen shot 2015-02-27 at 5 12 22 pm](https://cloud.githubusercontent.com/assets/1239550/6408209/ee707ce0-bea3-11e4-92ee-7adaacb5bece.png)
![screen shot 2015-02-27 at 5 14 52 pm](https://cloud.githubusercontent.com/assets/1239550/6408236/3a07e986-bea4-11e4-8e15-9a9e3d536903.png)
![screen shot 2015-02-27 at 5 15 02 pm](https://cloud.githubusercontent.com/assets/1239550/6408234/39bbed38-bea4-11e4-8bd6-b3cc3b3cc3df.png)
![screen shot 2015-02-27 at 5 15 09 pm](https://cloud.githubusercontent.com/assets/1239550/6408235/39d8e2bc-bea4-11e4-97e3-18527ad38bad.png)

**Comment by mlandauer** [comment]
All done now I think
